name: Django CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        include:
          - python-version: 3.7
            django-version: Django==3.1

          - python-version: 3.8
            django-version: Django==3.1

          - python-version: 3.7
            django-version: Django==3.2

          - python-version: 3.8
            django-version: Django==3.2

    services:
      elasticsearch:
        image: elasticsearch:7.6.2
        env:
          discovery.type: single-node
        options: >-
          --health-cmd "curl http://localhost:9200/_cluster/health"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10
        ports:
        - 9200:9200
      dynamodb:
        image: amazon/dynamodb-local
        ports:
          - 8000:8000

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        cd example
        pip install ${{ matrix.django-version }}
        pip install -r requirements/dependency_base.txt
        pip install -r requirements/base.txt
    - name: Flake
      run: |
        flake8 --config .config/flake8 is_core
    - name: Run Tests
      run: |
        cd example
        coverage run --omit */site-packages/*,*/migrations/*,*/lib/* manage.py test issue_tracker.tests --settings=dj.settings.settings -v 2
    - name: Coveralls
      uses: AndreMiras/coveralls-python-action@develop
      with:
        parallel: true
        flag-name: Unit Test

  coveralls_finish:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Coveralls Finished
      uses: AndreMiras/coveralls-python-action@develop
      with:
        parallel-finished: true
